-- GENERATED FILE. DO NOT EDIT.
-- Source of truth: backend/db/migrations/*.sql + checksums.json.
-- Generated by executing the ordered migration set in disposable MySQL and reading SHOW CREATE TABLE.
-- This inspection snapshot is not proof that migrations ran in any candidate or production environment.
-- snapshot_format: myroot-mysql-schema-snapshot:v1
-- mysql_engine_family: 8.0
-- migration_set_sha256: 23adfe30cd04dc84d0e415b0fb2c1832a14ae2f2fd564aa93314b1d38b8ef8bc
-- schema_body_sha256: a79b0b41c7102750a81af10d94a44c31e33ba5d8a82b4edcbd79d5da93f57ddc
-- table_count: 25
-- migration: 001_store_snapshot.sql sha256:57f0c3032dea218ad010f41ee4e9af6667ea4ae8f13c76096bc67f56763792e0
-- migration: 002_core_relational.sql sha256:62362767da1748f1aa7e2ec974677b410f123b1c002f2f1519102f19ff905821
-- migration: 003_privacy_consent.sql sha256:5758b1040533ef411361c8a2aad251497dfad7fb353348d6c887d3856bd68631
-- migration: 004_external_evidence_minimization.sql sha256:64c9ba3325c3950732fa09daf07ead178cccf5b661b012944dac32abf4976ac3
-- migration: 005_notification_subscription_grants.sql sha256:ce3d429e8de8608caf8faf5ef39d6de1566cd94558449e245476a26ee58a3909
-- migration: 006_command_event_foundation.sql sha256:723c148f24df8edb456362da47fec8105bda643c9f78500b093ac6b6d4e44857
-- migration: 007_command_recovery_lease.sql sha256:0916e7f855bafdf69aaeafd153649b04b1fb622471555348ea296a7eceb9504d
-- migration: 008_command_scope_crypto_metadata.sql sha256:b8ce188acb22ef713d2fe2e92d7643f99152a8e88dd8b03c03d878965a814b2a
-- migration: 009_outbox_dispatcher_fencing.sql sha256:a897d65edf8b5b87e5394264536e4c1998906d94d9b45e941ac8ca0f09183d54
-- migration: 010_durable_inbox_checkpoint.sql sha256:4f298d03d28c76c8046908866c1cf4de8306851b536aaadacd7d6d90ae0c5be2
-- migration: 011_durable_consumer_checkpoint.sql sha256:fd5dd674e526d271652070d361d9c48cdd049581718a3c6a570a1ca93388ff47
-- migration: 012_durable_inbox_dead_letter.sql sha256:6e1fd02fb7f8c80b6bc94482895e3c8396d76120d19fa8e2e48ae996178cdeec
-- migration: 013_inbox_content_protection_metadata.sql sha256:6f39bf27595c65de9787281ac7754e66377a75464986f2a5a3377a3ad52b8e38
-- migration: 014_inbox_handler_identity.sql sha256:9e0999b6583282a14b0e7e031c6a51ab4830a922e7599a342cd839d6fee87d02
-- migration: 015_task_share_completion_projection.sql sha256:772905d013a9b6a80dbf7073281deaae0aa1f7077a92eaed48e6a9c8ffa761d3
-- migration: 016_inbox_replay_run.sql sha256:1ed341bfc59a655be03910b0229138c0a412571403cbd6bdd16cc9588cd239b8
-- migration: 017_task_share_completion_shadow_projection.sql sha256:658ae562e9a19b68a04c2427d17ce8b841d9145bb7a56aa5ca30bfe91a1e27c7
-- migration: 018_notification_subscription_attempt.sql sha256:5746a1adf4105c2a1bfe50d28389c6e070101817061e0352af27905a72a752fe
-- migration: 019_notification_subscription_grant.sql sha256:55b8a33171df856b58e448cadd158ba0e7af414123a0a91cd2849a7a8bc3d9bb
-- migration: 020_notification_job.sql sha256:34b31679b8b9f1fada28182a17d299a776dfe7c524aec2a5bcf52537491193d1
-- migration: 021_notification_send_attempt.sql sha256:3a1045dd549d42f3e76baaa668362ad5ef6e17c43a4ebbcb11dcd7dc471bbcf4
-- migration: 022_notification_send_attempt_transition.sql sha256:38681ef5e508ff2a4d480a35165f03c810cba38a0062d9df44f8d829db0cddcb
-- migration: 023_inbox_replay_executor_identity.sql sha256:84a1876a4b573f645b2cbecf6da67cd1634c4b20f070222b34364636f063c0fa
-- migration: 024_notification_native_decision_contract.sql sha256:817b1e83864b475a8c80711ef181136bebc7aaf53148793d16748d14f5b86418
-- migration: 025_notification_job_request_identity.sql sha256:2250462991ab547fbb57c28cca67c91d2999a87a7ea6785f3ea52cff4f17042e
-- migration: 026_notification_send_attempt_receipt_metadata.sql sha256:cbeedd89b84c3f15b3eee3136536e0f4d02dd733b6fd3ad610ef9725bd37ad5e
-- migration: 027_notification_send_transition_receipt_metadata.sql sha256:b8db4701daa83785c0e8f5c142dcdac6807c239863cdd6e60a280a13961f62b9
-- migration: 028_migration_contract_registry.sql sha256:cd4f8eabeb07c4642e6c9acdc170e5d85b98526e28c4c23661d9d9a070d035c1
-- migration: 029_migration_run.sql sha256:489e429e25b2f0242794a91e969916dd3a0383a35186f67033996b7c17610e6e
-- migration: 030_migration_lineage.sql sha256:a44e6e8f5b2c02ec2e9ddb3e997b658adb8a8eef581a0b67d1c31b915cd86a18
-- migration: 031_task_share_migration_projection.sql sha256:b1fb65c5ed4cf15b7ef2b9d58c03bfbb34246d9b47224f794b0388af89f47261
-- migration: 032_v1_runtime_cycle.sql sha256:5f037db99648d3a3fdb4d80672fed80bdff54ba001326b6b761bc0aad40bc219
-- migration: 033_v1_runtime_alert.sql sha256:6cfd007977bd81cf51743338646e9f13f07a505e05236e9ea0e17af9b2c7014a
-- migration: 034_activity_module.sql sha256:e031706bc52025855339665971629226931a1c2d8d3f85fd381cbe911f43def6
-- migration: 035_activity_publication_session_event.sql sha256:d5e37c2f4ed7849f0998e8defc115c9438037f185465583b080ef3dcb7c10832
-- migration: 036_activity_enrollment_event_generation_stage.sql sha256:9caef234334cc06d469529d485d323e0736229f42876907d7d3f3b663164a712
-- migration: 037_activity_enrollment_event_generation_backfill.sql sha256:127edaaf9c2f85769a4aa5a3c17a8f11bb04dc99ebc5ac537d6cf3585e448327
-- migration: 038_activity_enrollment_event_generation_enforce.sql sha256:aff2145de7afb470b56ba39468727d3129ad86f22844ec1658da67844e14d0da
-- migration: 039_activity_session_event.sql sha256:46604e7c7b01491ffa55b00f1d503ebaf80dda9d42985add88823c945640ba50
-- migration: 040_activity_p0_content_and_session_policy.sql sha256:47957cd009b26ce848e9635f17d5e29b73e57bb956ffbff077a22a5d0ad03e59
-- migration: 041_task_activity_assignment.sql sha256:ebb606a5353496a68a87e037ffaafd9dcec92e92d519467cfe0a6f140c90670c
-- migration: 042_task_source_invalidation_event.sql sha256:34ab843b51b0884eeb2a8d3e808a3b010aac8b79d60900d15cb6c3aa1a23e16f
-- migration: 043_activity_session_cancel_close_stage.sql sha256:f2c6973873e7f5681f952102d58230a40d2237c92a24c2dcd1c5f81da6d0d7cb
-- migration: 044_activity_session_cancel_close_backfill.sql sha256:4081a8066c67853b4c2250c77608bd98c73ec79bc1732cf74aade15866431929
-- migration: 045_activity_session_policy_enforce.sql sha256:17c23ecb96b34fe0d531a749093fadaae496ade366fb39192abaeadad7590855
-- migration: 046_task_event_idempotency_scope_stage.sql sha256:b05eedef6686c6d7f7213bde8a20f5cc9a6043567a5bfb9491b7f74793a11cf6
-- migration: 047_task_event_idempotency_scope_backfill.sql sha256:37f101458e8a98631b9d96cf2a4956d0be78afcc391f7880d48bde18f24362d7
-- migration: 048_task_event_idempotency_scope_enforce.sql sha256:f149dbd865693ff875a14573e0d69ef21d19db329bf37e89d208f6f2b23185ac
-- migration: 049_wechat_unionid_provenance_stage.sql sha256:ac7425acfb125d25869cc27b95bbb6074b63b274851d9b35e014b5c306e3fc4d
-- migration: 050_wechat_unionid_provenance_backfill.sql sha256:3e447d2a01574fd1ea5f1c69da17f30d2e868b47264403fd50516aa22b6761c9
-- migration: 051_wechat_unionid_provenance_enforce.sql sha256:df9b2629aa23c9730d319f1b5ab700f90b7ee5e10e2c7ba3e8be4a4d7eec2019
-- migration: 052_notification_recipient_binding_legacy_stage.sql sha256:4c83d466b9e9bfd7c955df3bf65e8a232ecb20251fb9df4373cc73a773f468ba
-- migration: 053_notification_recipient_binding_v1_stage.sql sha256:45a9ffe533e5de674180891bb6da1b748d4958938d1ce86ce51f0040cb98f945
-- migration: 054_notification_recipient_binding_legacy_backfill.sql sha256:053c0464c37a98f56802dca4cb3b40ab888060570d22757fbf62800075b7173d
-- migration: 055_notification_recipient_binding_v1_backfill.sql sha256:c72c290c4d376b8cb973a3d763a01b814a602d1d943f8a1a4c2c4626d3585bc7
-- migration: 056_notification_recipient_binding_legacy_enforce.sql sha256:812b2f9444c46e07894e4cc30e0cdf6bc5563201cb956444f7d783dcc98dcf9b
-- migration: 057_notification_recipient_binding_v1_enforce.sql sha256:9e8785c730a5945991fb027c623c661d467aa1d9ab6e9b0ae638039a4ac9ba9b
-- migration: 058_notification_provider_call_fence_stage.sql sha256:1eca2f1171127f851ce06f0c30f728d9231853f15dc8e3e5fc6411acbe95231f
-- migration: 059_notification_provider_call_fence_backfill.sql sha256:1092eb6929f7e2e6aa54cffbe91e8c862ec1bf28abc6c57751545dc60fa2de81
-- migration: 060_notification_provider_call_fence_enforce.sql sha256:158d5fbfaa8d02a3ed7a65effe3b5d03a85649ab9c5e7e8c1c0cb9323eef711a
-- migration: 061_v1_runtime_alert_delivery.sql sha256:dff221a9835467d6c9d127ea8fadad128f20b1fb881ea30fd311fcea41cbce92
-- migration: 062_settlement_source_authority.sql sha256:d56a83a213290e4d62937bf41dd0ab44430d3d4f87eee0603692133afbf166a3
-- migration: 063_v1_runtime_alert_database_authority_stage.sql sha256:2cad7a116e725d1463312b619eb5f34312b653b364964a5b208fbe42e4c61b36
-- migration: 064_v1_runtime_control_ledger_database_authority.sql sha256:ff3e05241cc024fe3ba533a325bfd65df08421a02a7f7e7e274ef80328f86e9e
-- migration: 065_v1_runtime_alert_registration_return_row.sql sha256:263a4edb996596d9c8868471006ddc636e904dc17e7ce39813495fd3db20f39e
-- migration: 066_v1_runtime_alert_delivery_severity_slo_authority.sql sha256:411f29a8ac26eb8ee3261555bdbd33c20f46dde315fa7d642b308d4b832e64ac
-- migration: 067_formal_launch_retired_runtime_cleanup.sql sha256:ffb01a40da73c2b73794b2df72cb8d5f019c43c84fd161ccbda7b226f900e3a2
-- migration: 068_formal_launch_confirmed_prelaunch_cleanup.sql sha256:d2d867474c0fbc93cc5aec91b9ee18a03e8100331d66cc071bfb1f51b1189d31
-- migration: 069_health_assessment.sql sha256:2d04281d7af291c349c4fbce7b1dba8a9c80c2c49a4677f2db5475dc4a503a1c
-- migration: 070_growth_engagement.sql sha256:db4f76619459c058b0a7bb8be44d3986131bb363affa472eee5600e4e8315e0c
-- migration: 071_product_analytics.sql sha256:646f786fde31acbf3f2009a2dfb27f01e80fa35dc12d3e7e15138cd8722d1f35
-- migration: 072_health_advice_snapshot.sql sha256:7af77293b5d63f31c54fd33a8817f85bbc895b66c569e7e8bf76e642f9132fb8
-- migration: 073_channel_code_funnel.sql sha256:e5070d0a816d7f561d8cec6a599bce3990d97827b510b5375ededf88d23cfb85

SET NAMES utf8mb4;
SET time_zone = '+08:00';

-- table: activity_definition_version
CREATE TABLE `activity_definition_version` (
  `activity_version_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `activity_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `version` int unsigned NOT NULL,
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `title` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `summary` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `objective` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `audience` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `agenda` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `organizer` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `fee_description` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `bring_items` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `cancel_policy` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `privacy_notice_text` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `photography_notice_text` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `contact_display` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `detail_version` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `city` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `venue_summary` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `activity_type` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `hero_asset_ref` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `privacy_notice_ref` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `photography_notice_ref` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `content_approval_ref` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `contact_owner_signer_ref` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `review_reason_code` varchar(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `review_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reviewer_signer_ref` varchar(160) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `publish_owner_signer_ref` varchar(160) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `publication_authorization_adapter_id` varchar(160) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `publication_authorization_decision_ref` varchar(160) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `publication_authorized_principal_ref` varchar(160) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `controlled_approval_ref` varchar(160) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `content_authorization_digest` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `ued_acceptance_digest` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `photography_authorization_digest` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `artifact_provenance_digest` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `authorization_verified_at` datetime(3) DEFAULT NULL,
  `withdraw_owner_signer_ref` varchar(160) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `withdraw_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `archive_owner_signer_ref` varchar(160) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `archive_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `visibility` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `member_requirement` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `prebound_task_definition_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `prebound_task_definition_version` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `published_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`activity_version_id`),
  UNIQUE KEY `uk_activity_definition_version` (`activity_id`,`version`),
  UNIQUE KEY `uk_activity_definition_publication_decision` (`publication_authorization_adapter_id`,`publication_authorization_decision_ref`),
  KEY `idx_activity_definition_publish` (`status`,`city`,`activity_type`,`published_at`),
  CONSTRAINT `chk_activity_definition_archive_shape` CHECK ((((`status` = _ascii'ARCHIVED') and (`archive_owner_signer_ref` is not null) and (`archive_reason` is not null)) or (`status` <> _ascii'ARCHIVED'))),
  CONSTRAINT `chk_activity_definition_authorization_shape` CHECK ((((`status` = _ascii'PUBLISHED') and (`publication_authorization_adapter_id` is not null) and (`publication_authorization_decision_ref` is not null) and (`publication_authorized_principal_ref` is not null) and (`controlled_approval_ref` is not null) and (`controlled_approval_ref` = `content_approval_ref`) and (`content_authorization_digest` is not null) and regexp_like(`content_authorization_digest`,_ascii'^[a-f0-9]{64}$') and (`ued_acceptance_digest` is not null) and regexp_like(`ued_acceptance_digest`,_ascii'^[a-f0-9]{64}$') and (`photography_authorization_digest` is not null) and regexp_like(`photography_authorization_digest`,_ascii'^[a-f0-9]{64}$') and (`artifact_provenance_digest` is not null) and regexp_like(`artifact_provenance_digest`,_ascii'^[a-f0-9]{64}$') and (`authorization_verified_at` is not null)) or (`status` <> _ascii'PUBLISHED'))),
  CONSTRAINT `chk_activity_definition_publish_shape` CHECK ((((`status` = _ascii'PUBLISHED') and (`publish_owner_signer_ref` is not null) and (`published_at` is not null)) or (`status` <> _ascii'PUBLISHED'))),
  CONSTRAINT `chk_activity_definition_review_reason` CHECK (((`review_reason_code` is null) or (`review_reason_code` = _ascii'CHANGES_REQUESTED'))),
  CONSTRAINT `chk_activity_definition_source` CHECK ((`source` = _ascii'OPS_BACKEND')),
  CONSTRAINT `chk_activity_definition_status` CHECK ((`status` in (_ascii'DRAFT',_ascii'IN_REVIEW',_ascii'PUBLISHED',_ascii'UNPUBLISHED',_ascii'ARCHIVED'))),
  CONSTRAINT `chk_activity_definition_version_positive` CHECK ((`version` > 0)),
  CONSTRAINT `chk_activity_definition_visibility` CHECK ((`visibility` in (_ascii'PUBLIC',_ascii'MEMBER')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: activity_enrollment
CREATE TABLE `activity_enrollment` (
  `activity_enrollment_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `activity_session_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `reason_code` varchar(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `attempt_generation` int unsigned NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`activity_enrollment_id`),
  UNIQUE KEY `uk_activity_enrollment_session_user` (`activity_session_id`,`root_user_id`),
  KEY `idx_activity_enrollment_user_status` (`root_user_id`,`status`,`updated_at`),
  KEY `idx_activity_enrollment_session_status` (`activity_session_id`,`status`,`updated_at`),
  CONSTRAINT `fk_activity_enrollment_session` FOREIGN KEY (`activity_session_id`) REFERENCES `activity_session` (`activity_session_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_activity_enrollment_user` FOREIGN KEY (`root_user_id`) REFERENCES `root_user` (`root_user_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_activity_enrollment_generation` CHECK ((`attempt_generation` > 0)),
  CONSTRAINT `chk_activity_enrollment_reason` CHECK (((`reason_code` is null) or (`reason_code` in (_utf8mb4'USER_CANCELED',_utf8mb4'SESSION_CANCELED',_utf8mb4'APPROVAL_REJECTED',_utf8mb4'REVIEW_TIMEOUT',_utf8mb4'CAPACITY_FULL',_utf8mb4'CAPACITY_FULL_AT_REVIEW',_utf8mb4'CUTOFF_PASSED',_utf8mb4'POLICY_BLOCKED',_utf8mb4'OPERATOR_CORRECTION')))),
  CONSTRAINT `chk_activity_enrollment_reason_shape` CHECK ((((`status` in (_utf8mb4'PENDING',_utf8mb4'CONFIRMED')) and (`reason_code` is null)) or ((`status` in (_utf8mb4'REJECTED',_utf8mb4'CANCELED')) and (`reason_code` is not null)))),
  CONSTRAINT `chk_activity_enrollment_status` CHECK ((`status` in (_utf8mb4'PENDING',_utf8mb4'CONFIRMED',_utf8mb4'REJECTED',_utf8mb4'CANCELED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: activity_enrollment_event
CREATE TABLE `activity_enrollment_event` (
  `activity_enrollment_event_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `activity_enrollment_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `activity_session_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `attempt_generation` int unsigned NOT NULL,
  `event_sequence` int unsigned NOT NULL,
  `operation` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `from_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `to_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `reason_code` varchar(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `request_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` datetime(3) NOT NULL,
  PRIMARY KEY (`activity_enrollment_event_id`),
  UNIQUE KEY `uk_activity_enrollment_event_request` (`request_id`),
  UNIQUE KEY `uk_activity_enrollment_event_sequence` (`activity_enrollment_id`,`event_sequence`),
  KEY `idx_activity_enrollment_event_session` (`activity_session_id`,`occurred_at`),
  KEY `idx_activity_enrollment_event_user` (`root_user_id`,`occurred_at`),
  CONSTRAINT `fk_activity_enrollment_event_enrollment` FOREIGN KEY (`activity_enrollment_id`) REFERENCES `activity_enrollment` (`activity_enrollment_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_activity_enrollment_event_session` FOREIGN KEY (`activity_session_id`) REFERENCES `activity_session` (`activity_session_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_activity_enrollment_event_user` FOREIGN KEY (`root_user_id`) REFERENCES `root_user` (`root_user_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_activity_enrollment_event_from_status` CHECK (((`from_status` is null) or (`from_status` in (_ascii'PENDING',_ascii'CONFIRMED',_ascii'REJECTED',_ascii'CANCELED')))),
  CONSTRAINT `chk_activity_enrollment_event_generation` CHECK ((`attempt_generation` > 0)),
  CONSTRAINT `chk_activity_enrollment_event_operation` CHECK ((`operation` in (_ascii'ENROLL',_ascii'REVIEW',_ascii'REVIEW_TIMEOUT',_ascii'CANCEL',_ascii'SESSION_CANCEL'))),
  CONSTRAINT `chk_activity_enrollment_event_sequence` CHECK ((`event_sequence` > 0)),
  CONSTRAINT `chk_activity_enrollment_event_to_status` CHECK ((`to_status` in (_ascii'PENDING',_ascii'CONFIRMED',_ascii'REJECTED',_ascii'CANCELED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: activity_session
CREATE TABLE `activity_session` (
  `activity_session_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `activity_version_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `approval_mode` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `capacity` int unsigned NOT NULL,
  `registration_open_at` datetime(3) NOT NULL,
  `registration_close_at` datetime(3) NOT NULL,
  `cancel_close_at` datetime(3) NOT NULL,
  `review_deadline` datetime(3) DEFAULT NULL,
  `session_start_at` datetime(3) NOT NULL,
  `session_end_at` datetime(3) NOT NULL,
  `allow_reapply` tinyint(1) NOT NULL DEFAULT '0',
  `cancel_reason` varchar(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `cancel_reason_detail` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`activity_session_id`),
  UNIQUE KEY `uk_activity_session_business_time` (`activity_version_id`,`session_start_at`),
  KEY `idx_activity_session_visible` (`status`,`session_start_at`,`activity_version_id`),
  KEY `idx_activity_session_registration` (`status`,`registration_open_at`,`registration_close_at`),
  KEY `fk_activity_session_version` (`activity_version_id`),
  CONSTRAINT `fk_activity_session_version` FOREIGN KEY (`activity_version_id`) REFERENCES `activity_definition_version` (`activity_version_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_activity_session_approval` CHECK ((`approval_mode` in (_ascii'AUTO',_ascii'MANUAL'))),
  CONSTRAINT `chk_activity_session_cancel_reason` CHECK (((`cancel_reason` is null) or (`cancel_reason` in (_ascii'OPERATOR_CANCELED',_ascii'WEATHER',_ascii'VENUE',_ascii'FORCE_MAJEURE',_ascii'OTHER')))),
  CONSTRAINT `chk_activity_session_cancel_shape` CHECK ((((`status` = _ascii'CANCELED') and (`cancel_reason` is not null)) or ((`status` <> _ascii'CANCELED') and (`cancel_reason` is null)))),
  CONSTRAINT `chk_activity_session_cancel_window` CHECK (((`registration_open_at` < `cancel_close_at`) and (`cancel_close_at` <= `session_start_at`))),
  CONSTRAINT `chk_activity_session_capacity` CHECK ((`capacity` > 0)),
  CONSTRAINT `chk_activity_session_other_reason` CHECK (((`cancel_reason` <> _ascii'OTHER') or (`cancel_reason_detail` is not null))),
  CONSTRAINT `chk_activity_session_review_deadline` CHECK ((((`approval_mode` = _ascii'MANUAL') and (`review_deadline` is not null)) or (`approval_mode` = _ascii'AUTO'))),
  CONSTRAINT `chk_activity_session_status` CHECK ((`status` in (_ascii'SCHEDULED',_ascii'OPEN',_ascii'CLOSED',_ascii'CANCELED',_ascii'ENDED'))),
  CONSTRAINT `chk_activity_session_time_order` CHECK (((`registration_open_at` < `registration_close_at`) and (`registration_close_at` <= `session_start_at`) and (`session_start_at` < `session_end_at`)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: activity_session_event
CREATE TABLE `activity_session_event` (
  `activity_session_event_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `activity_session_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `event_sequence` int unsigned NOT NULL,
  `operation` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `from_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `to_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `reason_code` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `reason_detail` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `request_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `actor_ref` varchar(160) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `occurred_at` datetime(3) NOT NULL,
  PRIMARY KEY (`activity_session_event_id`),
  UNIQUE KEY `uk_activity_session_event_request` (`request_id`),
  UNIQUE KEY `uk_activity_session_event_sequence` (`activity_session_id`,`event_sequence`),
  UNIQUE KEY `uk_activity_session_event_operation` (`activity_session_id`,`operation`),
  KEY `idx_activity_session_event_occurred` (`occurred_at`,`activity_session_id`),
  CONSTRAINT `fk_activity_session_event_session` FOREIGN KEY (`activity_session_id`) REFERENCES `activity_session` (`activity_session_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_activity_session_event_from_status` CHECK ((`from_status` in (_utf8mb4'SCHEDULED',_utf8mb4'OPEN',_utf8mb4'CLOSED'))),
  CONSTRAINT `chk_activity_session_event_operation` CHECK ((`operation` = _utf8mb4'SESSION_CANCELED')),
  CONSTRAINT `chk_activity_session_event_other_reason` CHECK (((`reason_code` <> _utf8mb4'OTHER') or (`reason_detail` is not null))),
  CONSTRAINT `chk_activity_session_event_reason` CHECK ((`reason_code` in (_utf8mb4'OPERATOR_CANCELED',_utf8mb4'WEATHER',_utf8mb4'VENUE',_utf8mb4'FORCE_MAJEURE',_utf8mb4'OTHER'))),
  CONSTRAINT `chk_activity_session_event_sequence` CHECK ((`event_sequence` > 0)),
  CONSTRAINT `chk_activity_session_event_to_status` CHECK ((`to_status` = _utf8mb4'CANCELED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: analytics_event
CREATE TABLE `analytics_event` (
  `analytics_event_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `event_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `payload_json` json NOT NULL,
  `source` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `occurred_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`analytics_event_id`),
  KEY `idx_analytics_event_name_time` (`event_name`,`occurred_at`),
  KEY `idx_analytics_event_user_time` (`root_user_id`,`occurred_at`),
  CONSTRAINT `fk_analytics_event_root_user` FOREIGN KEY (`root_user_id`) REFERENCES `root_user` (`root_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: campaign_popup_receipt
CREATE TABLE `campaign_popup_receipt` (
  `campaign_popup_receipt_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `login_session_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `campaign_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `popup_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `popup_version` int NOT NULL,
  `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `action_type` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `claimed_at` datetime(3) NOT NULL,
  `viewed_at` datetime(3) DEFAULT NULL,
  `acted_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`campaign_popup_receipt_id`),
  UNIQUE KEY `uk_campaign_popup_receipt_session` (`login_session_id`),
  KEY `idx_campaign_popup_receipt_campaign_time` (`campaign_id`,`claimed_at`),
  KEY `idx_campaign_popup_receipt_user_time` (`root_user_id`,`claimed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: channel_attribution
CREATE TABLE `channel_attribution` (
  `channel_attribution_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `channel_definition_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `channel_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `campaign_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_page` varchar(240) COLLATE utf8mb4_unicode_ci NOT NULL,
  `signature_key_id` varchar(48) COLLATE utf8mb4_unicode_ci NOT NULL,
  `signature_scheme` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `attributed_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`channel_attribution_id`),
  UNIQUE KEY `uk_channel_attribution_first_touch` (`root_user_id`),
  KEY `idx_channel_attribution_channel_time` (`channel_id`,`attributed_at`),
  KEY `fk_channel_attribution_definition` (`channel_definition_id`),
  CONSTRAINT `fk_channel_attribution_definition` FOREIGN KEY (`channel_definition_id`) REFERENCES `channel_definition` (`channel_definition_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: channel_attribution_attempt
CREATE TABLE `channel_attribution_attempt` (
  `channel_attribution_attempt_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `requested_channel_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `requested_campaign_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `requested_target_page` varchar(240) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `result` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `reason` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `occurred_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`channel_attribution_attempt_id`),
  KEY `idx_channel_attribution_attempt_user_time` (`root_user_id`,`occurred_at`),
  KEY `idx_channel_attribution_attempt_result_time` (`result`,`occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: channel_definition
CREATE TABLE `channel_definition` (
  `channel_definition_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `channel_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `campaign_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `signature_key_id` varchar(48) COLLATE utf8mb4_unicode_ci NOT NULL,
  `allowed_target_pages_json` json NOT NULL,
  `start_at` datetime(3) DEFAULT NULL,
  `end_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`channel_definition_id`),
  UNIQUE KEY `uk_channel_definition_channel` (`channel_id`),
  KEY `idx_channel_definition_campaign_status` (`campaign_id`,`status`,`start_at`,`end_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: channel_funnel_event
CREATE TABLE `channel_funnel_event` (
  `channel_funnel_event_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `channel_funnel_visit_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `channel_qr_code_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `channel_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `campaign_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `assessment_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `stage` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `occurred_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`channel_funnel_event_id`),
  UNIQUE KEY `uk_channel_funnel_event_stage` (`channel_funnel_visit_id`,`stage`,`assessment_id`),
  KEY `idx_channel_funnel_event_campaign_stage_time` (`campaign_id`,`channel_id`,`stage`,`occurred_at`),
  KEY `idx_channel_funnel_event_code_stage_time` (`channel_qr_code_id`,`stage`,`occurred_at`),
  KEY `fk_channel_funnel_event_root_user` (`root_user_id`),
  CONSTRAINT `fk_channel_funnel_event_code` FOREIGN KEY (`channel_qr_code_id`) REFERENCES `channel_qr_code` (`channel_qr_code_id`),
  CONSTRAINT `fk_channel_funnel_event_root_user` FOREIGN KEY (`root_user_id`) REFERENCES `root_user` (`root_user_id`),
  CONSTRAINT `fk_channel_funnel_event_visit` FOREIGN KEY (`channel_funnel_visit_id`) REFERENCES `channel_funnel_visit` (`channel_funnel_visit_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: channel_funnel_visit
CREATE TABLE `channel_funnel_visit` (
  `channel_funnel_visit_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `client_visit_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `channel_qr_code_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `short_code` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `channel_definition_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `channel_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `campaign_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_page` varchar(240) COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `assessment_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `opened_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`channel_funnel_visit_id`),
  UNIQUE KEY `uk_channel_funnel_visit_client` (`client_visit_id`),
  KEY `idx_channel_funnel_visit_code_time` (`channel_qr_code_id`,`opened_at`),
  KEY `idx_channel_funnel_visit_user_time` (`root_user_id`,`opened_at`),
  CONSTRAINT `fk_channel_funnel_visit_code` FOREIGN KEY (`channel_qr_code_id`) REFERENCES `channel_qr_code` (`channel_qr_code_id`),
  CONSTRAINT `fk_channel_funnel_visit_root_user` FOREIGN KEY (`root_user_id`) REFERENCES `root_user` (`root_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: channel_qr_code
CREATE TABLE `channel_qr_code` (
  `channel_qr_code_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `channel_definition_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `channel_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `campaign_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `short_code` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `label` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `target_page` varchar(240) COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `start_at` datetime(3) DEFAULT NULL,
  `end_at` datetime(3) DEFAULT NULL,
  `env_version` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_by` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`channel_qr_code_id`),
  UNIQUE KEY `uk_channel_qr_code_short_code` (`short_code`),
  KEY `idx_channel_qr_code_campaign_status` (`campaign_id`,`channel_id`,`status`),
  KEY `fk_channel_qr_code_definition` (`channel_definition_id`),
  CONSTRAINT `fk_channel_qr_code_definition` FOREIGN KEY (`channel_definition_id`) REFERENCES `channel_definition` (`channel_definition_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: command_idempotency
CREATE TABLE `command_idempotency` (
  `command_idempotency_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `command_name` varchar(96) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
  `actor_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL,
  `actor_type` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `idempotency_key` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `request_digest` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `request_digest_scheme` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'sha256:v0',
  `request_digest_key_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `request_json` json DEFAULT NULL,
  `status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `attempt_count` int unsigned NOT NULL DEFAULT '0',
  `result_json` json DEFAULT NULL,
  `result_ref` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `result_codec_version` varchar(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `result_key_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `error_json` json DEFAULT NULL,
  `last_attempt_request_id` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lease_owner` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lease_expires_at` datetime(3) DEFAULT NULL,
  `lease_generation` bigint unsigned NOT NULL DEFAULT '0',
  `started_at` datetime(3) DEFAULT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  `failed_at` datetime(3) DEFAULT NULL,
  `retain_until` datetime(3) DEFAULT NULL,
  `retention_policy_version` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'command-retention-v1',
  `tombstoned_at` datetime(3) DEFAULT NULL,
  `tombstone_reason` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`command_idempotency_id`),
  UNIQUE KEY `uk_command_idempotency_scope` (`command_name`,`actor_id`,`idempotency_key`),
  KEY `idx_command_idempotency_status` (`status`,`updated_at`),
  KEY `idx_command_idempotency_retention` (`retain_until`,`tombstoned_at`),
  KEY `idx_command_idempotency_recovery` (`status`,`lease_expires_at`,`command_idempotency_id`),
  KEY `idx_command_idempotency_digest_crypto` (`request_digest_scheme`,`request_digest_key_id`,`command_idempotency_id`),
  KEY `idx_command_idempotency_result_crypto` (`result_codec_version`,`result_key_id`,`command_idempotency_id`),
  KEY `idx_command_idempotency_retention_policy` (`retention_policy_version`,`retain_until`,`tombstoned_at`),
  KEY `idx_command_idempotency_tombstone` (`tombstoned_at`,`tombstone_reason`,`command_idempotency_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: health_advice_snapshot
CREATE TABLE `health_advice_snapshot` (
  `health_advice_snapshot_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `initial_assessment_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `gut_assessment_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `states_json` json NOT NULL,
  `advice_json` json NOT NULL,
  `advice_source` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `adapter_id` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `model_name` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `prompt_version` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content_version` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `rule_version` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,
  `generated_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`health_advice_snapshot_id`),
  UNIQUE KEY `uk_health_advice_snapshot_inputs` (`root_user_id`,`initial_assessment_id`,`gut_assessment_id`,`prompt_version`),
  KEY `idx_health_advice_snapshot_user_time` (`root_user_id`,`generated_at`),
  KEY `fk_health_advice_snapshot_initial` (`initial_assessment_id`),
  KEY `fk_health_advice_snapshot_gut` (`gut_assessment_id`),
  CONSTRAINT `fk_health_advice_snapshot_gut` FOREIGN KEY (`gut_assessment_id`) REFERENCES `health_assessment_attempt` (`assessment_id`),
  CONSTRAINT `fk_health_advice_snapshot_initial` FOREIGN KEY (`initial_assessment_id`) REFERENCES `health_assessment_attempt` (`assessment_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: health_assessment_attempt
CREATE TABLE `health_assessment_attempt` (
  `assessment_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `assessment_definition_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `assessment_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `questionnaire_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `questionnaire_version` int NOT NULL,
  `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `safety_state` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_retest` tinyint(1) NOT NULL DEFAULT '0',
  `answers_json` json NOT NULL,
  `dimensions_json` json NOT NULL,
  `result_json` json NOT NULL,
  `result_copy_version` int NOT NULL,
  `source_channel` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_campaign_id` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_qr_code_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_visit_id` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `started_at` datetime(3) NOT NULL,
  `completed_at` datetime(3) DEFAULT NULL,
  `health_data_redacted_at` datetime(3) DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`assessment_id`),
  KEY `idx_health_assessment_attempt_user_type_time` (`root_user_id`,`assessment_type`,`completed_at`),
  KEY `idx_health_assessment_attempt_questionnaire` (`questionnaire_id`,`questionnaire_version`,`status`),
  KEY `fk_health_assessment_attempt_definition` (`assessment_definition_id`),
  KEY `idx_health_assessment_attempt_channel_source` (`source_campaign_id`,`source_qr_code_id`,`completed_at`),
  CONSTRAINT `fk_health_assessment_attempt_definition` FOREIGN KEY (`assessment_definition_id`) REFERENCES `health_assessment_definition` (`assessment_definition_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: health_assessment_definition
CREATE TABLE `health_assessment_definition` (
  `assessment_definition_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `assessment_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `questionnaire_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `questionnaire_version` int NOT NULL,
  `title` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci,
  `estimated_minutes` int NOT NULL DEFAULT '0',
  `status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content_review_status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `professional_review_status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `compliance_review_status` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `result_copy_version` int NOT NULL,
  `questions_json` json NOT NULL,
  `dimensions_json` json NOT NULL,
  `safety_rules_json` json NOT NULL,
  `result_rules_json` json NOT NULL,
  `result_copies_json` json NOT NULL,
  `default_result_code` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`assessment_definition_id`),
  UNIQUE KEY `uk_health_assessment_definition_questionnaire` (`questionnaire_id`,`questionnaire_version`),
  KEY `idx_health_assessment_definition_type_status` (`assessment_type`,`status`,`questionnaire_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: privacy_consent_record
CREATE TABLE `privacy_consent_record` (
  `privacy_consent_record_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `consent_type` varchar(48) COLLATE utf8mb4_unicode_ci NOT NULL,
  `policy_version` varchar(96) COLLATE utf8mb4_unicode_ci NOT NULL,
  `decision` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `purposes_json` json NOT NULL,
  `data_categories_json` json NOT NULL,
  `source_channel` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `occurred_at` datetime(3) NOT NULL,
  `created_at` datetime(3) NOT NULL,
  PRIMARY KEY (`privacy_consent_record_id`),
  KEY `idx_privacy_consent_user_type_time` (`root_user_id`,`consent_type`,`occurred_at`),
  KEY `idx_privacy_consent_policy_decision` (`policy_version`,`decision`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: questionnaire_answer
CREATE TABLE `questionnaire_answer` (
  `questionnaire_answer_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `campaign_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `questionnaire_id` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `version` int NOT NULL,
  `answers_json` json NOT NULL,
  `submitted_at` datetime(3) NOT NULL,
  `idempotency_key` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`questionnaire_answer_id`),
  UNIQUE KEY `uk_questionnaire_answer_idempotency` (`idempotency_key`),
  KEY `idx_questionnaire_answer_user_campaign` (`root_user_id`,`campaign_id`,`questionnaire_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: root_store_snapshot
CREATE TABLE `root_store_snapshot` (
  `store_key` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,
  `schema_version` int NOT NULL,
  `revision` bigint unsigned NOT NULL DEFAULT '0',
  `payload_json` json NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`store_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: root_user
CREATE TABLE `root_user` (
  `root_user_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `unionid` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lifecycle_status` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_channel` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unionid_status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`root_user_id`),
  UNIQUE KEY `uk_root_user_unionid` (`unionid`),
  KEY `idx_root_user_lifecycle_status` (`lifecycle_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: schema_migrations
CREATE TABLE `schema_migrations` (
  `version` varchar(96) COLLATE utf8mb4_unicode_ci NOT NULL,
  `checksum` char(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `applied_at` datetime(3) NOT NULL,
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: user_contact_method
CREATE TABLE `user_contact_method` (
  `contact_method_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contact_type` varchar(24) COLLATE utf8mb4_unicode_ci NOT NULL,
  `phone_masked` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phone_hash` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `verified` tinyint(1) NOT NULL DEFAULT '0',
  `evidence` json DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  PRIMARY KEY (`contact_method_id`),
  UNIQUE KEY `uk_user_contact_method_type` (`root_user_id`,`contact_type`),
  KEY `idx_user_contact_method_phone_hash` (`phone_hash`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: user_lifecycle_event
CREATE TABLE `user_lifecycle_event` (
  `lifecycle_event_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `event_type` varchar(48) COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_channel` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_code` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `metadata` json DEFAULT NULL,
  `occurred_at` datetime(3) NOT NULL,
  PRIMARY KEY (`lifecycle_event_id`),
  KEY `idx_user_lifecycle_event_user_time` (`root_user_id`,`occurred_at`),
  KEY `idx_user_lifecycle_event_type_time` (`event_type`,`occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- table: wechat_identity
CREATE TABLE `wechat_identity` (
  `wechat_identity_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `root_user_id` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `app_code` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,
  `openid` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `unionid` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unionid_status` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,
  `unionid_trust_status` varchar(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'UNVERIFIED',
  `unionid_provenance_source` varchar(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `unionid_verified_at` datetime(3) DEFAULT NULL,
  `unionid_provenance_canonical_version` varchar(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `unionid_provenance_digest` char(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `unionid_provenance_digest_scheme` varchar(64) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `unionid_provenance_key_id` varchar(128) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL,
  `created_at` datetime(3) NOT NULL,
  `updated_at` datetime(3) NOT NULL,
  `last_seen_at` datetime(3) NOT NULL,
  PRIMARY KEY (`wechat_identity_id`),
  UNIQUE KEY `uk_wechat_identity_app_openid` (`app_code`,`openid`),
  UNIQUE KEY `uk_wechat_identity_root_app` (`root_user_id`,`app_code`),
  KEY `idx_wechat_identity_root_user` (`root_user_id`),
  KEY `idx_wechat_identity_unionid` (`unionid`),
  KEY `idx_wechat_identity_unionid_authority` (`unionid`,`unionid_trust_status`,`root_user_id`),
  KEY `idx_wechat_identity_provenance_crypto` (`unionid_provenance_digest_scheme`,`unionid_provenance_key_id`,`wechat_identity_id`),
  CONSTRAINT `chk_wechat_identity_unionid_provenance` CHECK ((((`unionid_trust_status` = _utf8mb4'UNVERIFIED') and (`unionid_status` is not null) and (`unionid_status` = _utf8mb4'PENDING') and (`unionid_provenance_source` is null) and (`unionid_verified_at` is null) and (`unionid_provenance_canonical_version` is null) and (`unionid_provenance_digest` is null) and (`unionid_provenance_digest_scheme` is null) and (`unionid_provenance_key_id` is null)) or ((`unionid_trust_status` = _utf8mb4'VERIFIED') and (`unionid` is not null) and (`unionid_status` is not null) and (`unionid_status` = _utf8mb4'LINKED') and (`unionid_provenance_source` is not null) and (`unionid_provenance_source` in (_utf8mb4'CLOUDBASE',_utf8mb4'WECHAT_GATEWAY',_utf8mb4'WECHAT_CODE2SESSION')) and (`unionid_verified_at` is not null) and (`unionid_provenance_canonical_version` is not null) and (`unionid_provenance_canonical_version` = _utf8mb4'canonical-json:v1') and (`unionid_provenance_digest` is not null) and regexp_like(`unionid_provenance_digest`,_utf8mb4'^[0-9a-f]{64}$') and (`unionid_provenance_digest_scheme` is not null) and (`unionid_provenance_digest_scheme` = _utf8mb4'hmac-sha256:v1') and (`unionid_provenance_key_id` is not null) and regexp_like(`unionid_provenance_key_id`,_utf8mb4'^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$'))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
