const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const {
  applyMysqlMigrations,
  listMigrationFiles,
  migrationChecksum,
} = require("./mysqlMigrations");

const DEFAULT_MIGRATIONS_DIR = path.join(__dirname, "..", "db", "migrations");
const DEFAULT_SNAPSHOT_PATH = path.join(__dirname, "..", "db", "schema.sql");
const SNAPSHOT_FORMAT = "myroot-mysql-schema-snapshot:v1";
const LOCAL_HOSTS = new Set(["127.0.0.1", "localhost", "::1"]);
const DISPOSABLE_SERVER_MARKER_SCHEMA = "myroot_schema_snapshot_sandbox_marker";

function sha256(value) {
  return crypto.createHash("sha256").update(value).digest("hex");
}

function plainRecord(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function schemaSnapshotError(code, message) {
  const error = new Error(message || code);
  error.code = code;
  return error;
}

function compareAscii(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function quoteIdentifier(value) {
  const identifier = String(value || "");
  if (!/^[a-z][a-z0-9_]{0,63}$/i.test(identifier)) {
    throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_IDENTIFIER_INVALID");
  }
  return `\`${identifier}\``;
}

function migrationSetDescriptor(options = {}) {
  const migrationsDir = options.migrationsDir || DEFAULT_MIGRATIONS_DIR;
  const manifestPath = options.manifestPath || path.join(migrationsDir, "checksums.json");
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
  const expected = plainRecord(manifest.files) ? manifest.files : {};
  const files = listMigrationFiles(migrationsDir);
  if (JSON.stringify(Object.keys(expected).sort(compareAscii)) !== JSON.stringify([...files].sort(compareAscii))) {
    throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_MIGRATION_SET_DRIFT");
  }
  const migrations = files.map((file) => {
    const sql = fs.readFileSync(path.join(migrationsDir, file), "utf8");
    const checksum = migrationChecksum(sql);
    if (expected[file] !== checksum) {
      throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_MIGRATION_CHECKSUM_DRIFT", file);
    }
    return Object.freeze({ file, checksum });
  });
  const migrationSetDigest = sha256(migrations
    .map(({ file, checksum }) => `${file}\u0000${checksum}\n`)
    .join(""));
  return Object.freeze({
    format: SNAPSHOT_FORMAT,
    migrations: Object.freeze(migrations),
    migrationSetDigest,
  });
}

function normalizeShowCreate(value) {
  return String(value || "")
    .replace(/\r\n/g, "\n")
    .trim();
}

function renderMysqlSchemaSnapshot(input = {}) {
  if (!plainRecord(input)
    || !plainRecord(input.descriptor)
    || input.descriptor.format !== SNAPSHOT_FORMAT
    || !Array.isArray(input.tables)
    || !/^\d+\.\d+$/.test(String(input.mysqlEngineFamily || ""))) {
    throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_INPUT_INVALID");
  }
  const tables = input.tables.map((entry) => {
    if (!plainRecord(entry)) throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_INPUT_INVALID");
    const tableName = String(entry.tableName || "");
    quoteIdentifier(tableName);
    const createSql = normalizeShowCreate(entry.createSql);
    if (!createSql.startsWith(`CREATE TABLE \`${tableName}\``)) {
      throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_CREATE_SQL_INVALID", tableName);
    }
    return Object.freeze({ tableName, createSql });
  }).sort((left, right) => compareAscii(left.tableName, right.tableName));
  if (new Set(tables.map((entry) => entry.tableName)).size !== tables.length) {
    throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_DUPLICATE_TABLE");
  }
  const body = tables.map(({ tableName, createSql }) => [
    `-- table: ${tableName}`,
    `${createSql};`,
  ].join("\n")).join("\n\n");
  const bodyDigest = sha256(`${body}\n`);
  const migrationLines = input.descriptor.migrations
    .map(({ file, checksum }) => `-- migration: ${file} sha256:${checksum}`)
    .join("\n");
  return [
    "-- GENERATED FILE. DO NOT EDIT.",
    "-- Source of truth: backend/db/migrations/*.sql + checksums.json.",
    "-- Generated by executing the ordered migration set in disposable MySQL and reading SHOW CREATE TABLE.",
    "-- This inspection snapshot is not proof that migrations ran in any candidate or production environment.",
    `-- snapshot_format: ${SNAPSHOT_FORMAT}`,
    `-- mysql_engine_family: ${input.mysqlEngineFamily}`,
    `-- migration_set_sha256: ${input.descriptor.migrationSetDigest}`,
    `-- schema_body_sha256: ${bodyDigest}`,
    `-- table_count: ${tables.length}`,
    migrationLines,
    "",
    "SET NAMES utf8mb4;",
    "SET time_zone = '+08:00';",
    "",
    body,
    "",
  ].join("\n");
}

function rowValue(row, key) {
  if (Object.prototype.hasOwnProperty.call(row, key)) return row[key];
  const lower = key.toLowerCase();
  const matched = Object.keys(row).find((candidate) => candidate.toLowerCase() === lower);
  return matched ? row[matched] : undefined;
}

async function captureMysqlSchemaSnapshot(pool, options = {}) {
  if (!pool || typeof pool.getConnection !== "function") {
    throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_POOL_INVALID");
  }
  const database = String(options.database || "");
  quoteIdentifier(database);
  const descriptor = options.descriptor || migrationSetDescriptor(options);
  const connection = await pool.getConnection();
  try {
    const [databaseRows] = await connection.query("SELECT DATABASE() AS current_database");
    const currentDatabase = Array.isArray(databaseRows)
      && databaseRows.length === 1
      && String(rowValue(databaseRows[0], "current_database") || "");
    if (currentDatabase !== database) {
      throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_DATABASE_DRIFT");
    }
    const [versionRows] = await connection.query("SELECT VERSION() AS server_version");
    const version = String(versionRows[0] && rowValue(versionRows[0], "server_version") || "");
    const familyMatch = version.match(/^(\d+\.\d+)/);
    if (!familyMatch || familyMatch[1] !== "8.0") {
      throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_ENGINE_UNSUPPORTED", version);
    }
    const [ledgerRows] = await connection.query(
      "SELECT version, checksum FROM schema_migrations ORDER BY version"
    );
    const expectedLedger = descriptor.migrations.map(({ file, checksum }) => ({ version: file, checksum }));
    const actualLedger = ledgerRows.map((row) => ({
      version: String(rowValue(row, "version") || ""),
      checksum: String(rowValue(row, "checksum") || ""),
    }));
    if (JSON.stringify(actualLedger) !== JSON.stringify(expectedLedger)) {
      throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_LEDGER_DRIFT");
    }
    const [tableRows] = await connection.execute(
      `
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = ?
          AND table_type = 'BASE TABLE'
        ORDER BY table_name
      `,
      [database]
    );
    const tables = [];
    for (const row of tableRows) {
      const tableName = String(rowValue(row, "table_name") || "");
      const [createRows] = await connection.query(
        `SHOW CREATE TABLE ${quoteIdentifier(database)}.${quoteIdentifier(tableName)}`
      );
      if (!Array.isArray(createRows) || createRows.length !== 1) {
        throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_CREATE_SQL_MISSING", tableName);
      }
      tables.push(Object.freeze({
        tableName,
        createSql: String(rowValue(createRows[0], "Create Table") || ""),
      }));
    }
    return renderMysqlSchemaSnapshot({
      descriptor,
      mysqlEngineFamily: familyMatch[1],
      tables,
    });
  } finally {
    connection.release();
  }
}

function assertLocalSnapshotHost(host) {
  if (!LOCAL_HOSTS.has(String(host || "").toLowerCase())) {
    throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_NON_LOCAL_HOST_FORBIDDEN");
  }
}

async function assertDisposableSnapshotServer(connection) {
  if (!connection || typeof connection.query !== "function") {
    throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_SERVER_CONNECTION_INVALID");
  }
  const [rows] = await connection.query(
    `
      SELECT schema_name
      FROM information_schema.schemata
      WHERE schema_name NOT IN ('information_schema', 'mysql', 'performance_schema', 'sys')
      ORDER BY schema_name
    `
  );
  const schemas = (Array.isArray(rows) ? rows : [])
    .map((row) => String(rowValue(row, "schema_name") || ""));
  if (schemas.length !== 1 || schemas[0] !== DISPOSABLE_SERVER_MARKER_SCHEMA) {
    throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_SERVER_NOT_DISPOSABLE");
  }
  const [objectRows] = await connection.query(
    `
      SELECT
        (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = ?)
        + (SELECT COUNT(*) FROM information_schema.routines WHERE routine_schema = ?)
        + (SELECT COUNT(*) FROM information_schema.triggers WHERE trigger_schema = ?)
        + (SELECT COUNT(*) FROM information_schema.events WHERE event_schema = ?)
          AS object_count
    `,
    Array(4).fill(DISPOSABLE_SERVER_MARKER_SCHEMA)
  );
  const objectCountValue = Array.isArray(objectRows)
    && objectRows.length === 1
    && rowValue(objectRows[0], "object_count");
  const objectCount = typeof objectCountValue === "string" && /^(?:0|[1-9][0-9]*)$/.test(objectCountValue)
    ? Number(objectCountValue)
    : objectCountValue;
  if (!Number.isSafeInteger(objectCount) || objectCount !== 0) {
    throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_SERVER_NOT_DISPOSABLE");
  }
}

async function generateIsolatedMysqlSchemaSnapshot(options = {}) {
  const mysql = options.mysql;
  if (!mysql || typeof mysql.createConnection !== "function" || typeof mysql.createPool !== "function") {
    throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_DRIVER_INVALID");
  }
  const host = String(options.host || "127.0.0.1");
  assertLocalSnapshotHost(host);
  const database = `myroot_schema_snapshot_${process.pid}_${crypto.randomBytes(8).toString("hex")}`;
  const serverConfig = {
    host,
    port: Number(options.port || 3306),
    user: String(options.user || "root"),
    password: String(options.password || ""),
    charset: "utf8mb4",
    timezone: "+08:00",
  };
  const descriptor = migrationSetDescriptor(options);
  let serverConnection;
  let pool;
  let databaseCreated = false;
  try {
    serverConnection = await mysql.createConnection(serverConfig);
    await assertDisposableSnapshotServer(serverConnection);
    await serverConnection.query(
      `CREATE DATABASE ${quoteIdentifier(database)} CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin`
    );
    databaseCreated = true;
    pool = mysql.createPool({
      ...serverConfig,
      database,
      connectionLimit: 4,
      waitForConnections: true,
      namedPlaceholders: false,
      dateStrings: true,
    });
    await applyMysqlMigrations(pool, {
      database,
      migrationsDir: options.migrationsDir || DEFAULT_MIGRATIONS_DIR,
      migrationLockTimeoutSeconds: 10,
    });
    return await captureMysqlSchemaSnapshot(pool, {
      database,
      descriptor,
      migrationsDir: options.migrationsDir || DEFAULT_MIGRATIONS_DIR,
    });
  } finally {
    let cleanupFailed = false;
    if (pool) {
      try { await pool.end(); } catch { cleanupFailed = true; }
    }
    if (serverConnection) {
      if (databaseCreated) {
        try { await serverConnection.query(`DROP DATABASE ${quoteIdentifier(database)}`); } catch { cleanupFailed = true; }
      }
      try { await serverConnection.end(); } catch { cleanupFailed = true; }
    }
    if (cleanupFailed) throw schemaSnapshotError("MYSQL_SCHEMA_SNAPSHOT_CLEANUP_FAILED");
  }
}

function verifyCommittedSnapshot(expectedSnapshot, options = {}) {
  const snapshotPath = options.snapshotPath || DEFAULT_SNAPSHOT_PATH;
  const actualSnapshot = fs.readFileSync(snapshotPath, "utf8");
  const matches = actualSnapshot === expectedSnapshot;
  return Object.freeze({
    matches,
    snapshotPath,
    expectedSha256: sha256(expectedSnapshot),
    actualSha256: sha256(actualSnapshot),
  });
}

function inspectCommittedSnapshotProvenance(options = {}) {
  const snapshotPath = options.snapshotPath || DEFAULT_SNAPSHOT_PATH;
  const snapshot = fs.readFileSync(snapshotPath, "utf8");
  const descriptor = migrationSetDescriptor(options);
  const formatMatch = snapshot.match(/^-- snapshot_format: (.+)$/m);
  const engineFamilyMatch = snapshot.match(/^-- mysql_engine_family: (.+)$/m);
  const migrationSetMatch = snapshot.match(/^-- migration_set_sha256: ([a-f0-9]{64})$/m);
  const bodyDigestMatch = snapshot.match(/^-- schema_body_sha256: ([a-f0-9]{64})$/m);
  const tableCountMatch = snapshot.match(/^-- table_count: (\d+)$/m);
  const generated = snapshot.startsWith("-- GENERATED FILE. DO NOT EDIT.\n");
  const migrationLines = [...snapshot.matchAll(/^-- migration: ([^ ]+) sha256:([a-f0-9]{64})$/gm)]
    .map((match) => ({ file: match[1], checksum: match[2] }));
  const expectedHeader = [
    "-- GENERATED FILE. DO NOT EDIT.",
    "-- Source of truth: backend/db/migrations/*.sql + checksums.json.",
    "-- Generated by executing the ordered migration set in disposable MySQL and reading SHOW CREATE TABLE.",
    "-- This inspection snapshot is not proof that migrations ran in any candidate or production environment.",
    `-- snapshot_format: ${SNAPSHOT_FORMAT}`,
    "-- mysql_engine_family: 8.0",
    `-- migration_set_sha256: ${descriptor.migrationSetDigest}`,
    `-- schema_body_sha256: ${bodyDigestMatch ? bodyDigestMatch[1] : ""}`,
    `-- table_count: ${tableCountMatch ? tableCountMatch[1] : ""}`,
    ...descriptor.migrations.map(({ file, checksum }) => `-- migration: ${file} sha256:${checksum}`),
    "",
    "SET NAMES utf8mb4;",
    "SET time_zone = '+08:00';",
    "",
    "",
  ].join("\n");
  const headerMatches = snapshot.startsWith(expectedHeader);
  const tableSection = headerMatches ? snapshot.slice(expectedHeader.length) : "";
  const actualBodyDigest = sha256(tableSection);
  const tableCount = [...tableSection.matchAll(/^-- table: /gm)].length;
  const matches = generated
    && formatMatch && formatMatch[1] === SNAPSHOT_FORMAT
    && engineFamilyMatch && engineFamilyMatch[1] === "8.0"
    && migrationSetMatch && migrationSetMatch[1] === descriptor.migrationSetDigest
    && bodyDigestMatch && bodyDigestMatch[1] === actualBodyDigest
    && tableCountMatch && Number(tableCountMatch[1]) === tableCount
    && headerMatches
    && JSON.stringify(migrationLines) === JSON.stringify(descriptor.migrations);
  return Object.freeze({
    matches: Boolean(matches),
    snapshotPath,
    format: formatMatch ? formatMatch[1] : "",
    mysqlEngineFamily: engineFamilyMatch ? engineFamilyMatch[1] : "",
    migrationSetDigest: migrationSetMatch ? migrationSetMatch[1] : "",
    expectedMigrationSetDigest: descriptor.migrationSetDigest,
    bodyDigest: bodyDigestMatch ? bodyDigestMatch[1] : "",
    actualBodyDigest,
    tableCount,
    expectedTableCount: tableCountMatch ? Number(tableCountMatch[1]) : -1,
  });
}

module.exports = {
  DEFAULT_MIGRATIONS_DIR,
  DEFAULT_SNAPSHOT_PATH,
  DISPOSABLE_SERVER_MARKER_SCHEMA,
  SNAPSHOT_FORMAT,
  assertDisposableSnapshotServer,
  captureMysqlSchemaSnapshot,
  generateIsolatedMysqlSchemaSnapshot,
  inspectCommittedSnapshotProvenance,
  migrationSetDescriptor,
  normalizeShowCreate,
  renderMysqlSchemaSnapshot,
  verifyCommittedSnapshot,
};
