const { nowISO } = require("./dates");

function createId(prefix) {
  return `${prefix}_${Math.random().toString(16).slice(2, 10)}${Date.now().toString(16).slice(-6)}`;
}

function createSeedData() {
  return {
    tokens: {},
    sessions: [],
    idempotency: {},
    commandIdempotencyRecords: [],
    eventOutbox: [],
    eventInbox: [],
    eventConsumerCheckpoints: [],
    users: [],
    rootUsers: [],
    wechatIdentities: [],
    formalProfiles: [],
    formalContentItems: [
      {
        contentId: "cnt_home_foundation",
        version: 1,
        placement: "HOME",
        status: "PUBLISHED",
        assetState: "DEVELOPMENT_PLACEHOLDER",
        kicker: "ROOT FOUNDATION",
        lines: ["把每天的选择，", "还给身体自己的节奏"],
        coverAssetUrl: "",
        detailImages: [],
        sortOrder: 10,
        startsAt: "2026-08-01T00:00:00.000Z",
        endsAt: "2099-01-01T00:00:00.000Z",
        action: null,
      },
      {
        contentId: "cnt_home_activity",
        version: 1,
        placement: "HOME",
        status: "PUBLISHED",
        assetState: "DEVELOPMENT_PLACEHOLDER",
        kicker: "ROOT / TOGETHER",
        lines: ["在线下相遇，", "重新感受身体的流动"],
        coverAssetUrl: "",
        detailImages: [],
        sortOrder: 20,
        startsAt: "2026-08-01T00:00:00.000Z",
        endsAt: "2099-01-01T00:00:00.000Z",
        action: { type: "MINIPROGRAM_PAGE", path: "/pages/activities/index" },
      },
    ],
    profiles: [],
    leadProfiles: [],
    identityLinks: [],
    userContactMethods: [],
    privacyConsentRecords: [],
    userLifecycleEvents: [],
    campaignDefinitions: [],
    campaignParticipants: [],
    activityDefinitionVersions: [],
    activitySessions: [],
    activitySessionEvents: [],
    activityEnrollments: [],
    activityEnrollmentEvents: [],
    taskDefinitions: [],
    taskEvents: [],
    notificationTemplates: [],
    notificationSubscriptions: [],
    notificationSubscriptionGrants: [],
    notificationJobs: [],
    notificationDeliveries: [],
    questionnaireAnswers: [],
    healthScaleResponses: [],
    healthContentVersions: [],
    campaignRuleVersions: [],
    settlementRecords: [],
    manualReviewItems: [],
    adminLifecycleFilterPresets: [],
    adminLifecycleSettlementJobs: [],
    adminLifecycleUserExports: [],
    operationalAlertRules: [],
    operationalAlertRuns: [],
    operationalAlertNotifications: [],
    releaseEvidenceArchives: [],
    releaseSignoffs: [],
    adminLegacyDeprecationDecisions: [],
    productionCutoverProofs: [],
    rootMemberCenterJumpProofs: [],
    consultationAdvisorAssignments: [],
    consultationWeworkWritebacks: [],
    weworkTouchJobs: [],
    orderAfterSalesRecords: [],
    youzanProducts: [
      {
        youzan_product_id: "ROOT_PREBIOTIC_TRIAL",
        title: "ROOT 益生菌试饮装",
        subtitle: "适合路演体验与 7 日身体记录",
        summary: "购买在 Root 会员中心完成，myRoot 负责记录、任务与奖励结算。",
        description: "商品信息来自 Root 会员中心快照。库存、价格和优惠以 Root 会员中心展示为准；用户可自行决定是否购买和参与打卡任务。",
        image_url: "/static/icon/shop.png",
        price_text: "价格以 Root 会员中心为准",
        status: "ACTIVE",
        badge: "路演推荐",
        youzan_app_id: "",
        youzan_path: "#小程序://ROOT会员中心/lnQOjYsk8gZoABH",
        raw_payload: {},
        created_at: nowISO(),
        updated_at: nowISO(),
        synced_at: nowISO(),
      },
    ],
    youzanSkus: [
      {
        youzan_sku_id: "ROOT_PREBIOTIC_TRIAL_DEFAULT",
        youzan_product_id: "ROOT_PREBIOTIC_TRIAL",
        sku_name: "默认规格",
        price: null,
        price_text: "以 Root 会员中心为准",
        stock_status: "UNKNOWN",
        raw_payload: {},
        created_at: nowISO(),
        updated_at: nowISO(),
      },
    ],
    campaignProductRelations: [
      {
        campaign_product_relation_id: "cpr_root_roadshow_trial",
        campaign_id: "ROOT_ROADSHOW_DEFAULT",
        youzan_product_id: "ROOT_PREBIOTIC_TRIAL",
        display_order: 10,
        badge: "推荐体验",
        created_at: nowISO(),
        updated_at: nowISO(),
      },
    ],
    productJumpLogs: [],
    youzanCustomers: [],
    youzanOrders: [
      {
        order_id: "ord_root_001",
        user_id: "",
        youzan_order_no: "YZROOT202604260001",
        phone: "13800000001",
        receiver_name: "王小路",
        receiver_phone: "13800000001",
        product_name: "ROOT 7日试饮装",
        product_id: "ROOT-PREBIOTIC-TRIAL",
        amount: 199,
        paid_at: "2026-04-26T10:12:00+08:00",
        order_status: "PAID",
        delivery_status: "DELIVERED",
        after_sales_status: "NONE",
        after_sales_no: "",
        refund_status: "NONE",
        refund_amount: 0,
        after_sales_updated_at: "",
        raw_address_text: "上海市演示地址1号",
        matched_at: "",
        match_source: "",
      },
      {
        order_id: "ord_root_002",
        user_id: "",
        youzan_order_no: "YZROOT202604260002",
        phone: "13800000002",
        receiver_name: "李小根",
        receiver_phone: "13800000002",
        product_name: "ROOT 7日试饮装",
        product_id: "ROOT-PREBIOTIC-TRIAL",
        amount: 199,
        paid_at: "2026-04-26T11:20:00+08:00",
        order_status: "PAID",
        delivery_status: "SHIPPED",
        after_sales_status: "NONE",
        after_sales_no: "",
        refund_status: "NONE",
        refund_amount: 0,
        after_sales_updated_at: "",
        raw_address_text: "杭州市演示地址2号",
        matched_at: "",
        match_source: "",
      },
      {
        order_id: "ord_root_used",
        user_id: "usr_finished",
        youzan_order_no: "YZROOT202604200099",
        phone: "13800000099",
        receiver_name: "陈已用",
        receiver_phone: "13800000099",
        product_name: "ROOT 7日试饮装",
        product_id: "ROOT-PREBIOTIC-TRIAL",
        amount: 199,
        paid_at: "2026-04-20T09:00:00+08:00",
        order_status: "PAID",
        delivery_status: "DELIVERED",
        after_sales_status: "NONE",
        after_sales_no: "",
        refund_status: "NONE",
        refund_amount: 0,
        after_sales_updated_at: "",
        raw_address_text: "北京市演示地址99号",
        matched_at: "2026-04-20T09:00:00+08:00",
        match_source: "AUTO_PHONE",
      },
    ],
    orderFulfillments: [
      {
        fulfillment_id: "ful_ord_root_001",
        order_id: "ord_root_001",
        receiver_name: "王小路",
        receiver_phone: "13800000001",
        carrier: "SF",
        tracking_no: "SFROOT0001",
        delivery_status: "DELIVERED",
        shipped_at: "2026-04-26T14:00:00+08:00",
        delivered_at: "2026-04-28T10:30:00+08:00",
        last_event_text: "已签收",
        updated_at: nowISO(),
      },
      {
        fulfillment_id: "ful_ord_root_002",
        order_id: "ord_root_002",
        receiver_name: "李小根",
        receiver_phone: "13800000002",
        carrier: "YTO",
        tracking_no: "YTOROOT0002",
        delivery_status: "SHIPPED",
        shipped_at: "2026-04-26T15:20:00+08:00",
        delivered_at: "",
        last_event_text: "运输中",
        updated_at: nowISO(),
      },
      {
        fulfillment_id: "ful_ord_root_used",
        order_id: "ord_root_used",
        receiver_name: "陈已用",
        receiver_phone: "13800000099",
        carrier: "SF",
        tracking_no: "SFROOT0099",
        delivery_status: "DELIVERED",
        shipped_at: "2026-04-20T11:00:00+08:00",
        delivered_at: "2026-04-22T16:20:00+08:00",
        last_event_text: "已签收",
        updated_at: nowISO(),
      },
    ],
    operationTasks: [],
    dailySummaries: [],
    externalSampleReviews: [],
    importBatches: [],
    externalStatusMappings: [],
    auditLogs: [],
    externalAdapterRuns: [],
    externalAdapterCursors: [],
    couponEvents: [],
    questionnaireDefinitions: [],
    questionnaireResponses: [],
    refundWorkItems: [],
    checkinSessions: [],
    checkinRecords: [],
    dailyCheckinRecords: [],
    refunds: [],
    eventsTrack: [],
    uploads: [],
    events: [
      {
        event_id: createId("evt"),
        type: "seed_loaded",
        message: "ROOT demo data initialized",
        created_at: nowISO(),
      },
    ],
  };
}

module.exports = {
  createId,
  createSeedData,
};
