-- Authoritative relational facts for scoped command idempotency and at-least-once
-- event transport. These tables are intentionally not snapshot projections.

CREATE TABLE IF NOT EXISTS command_idempotency (
  command_idempotency_id VARCHAR(64) PRIMARY KEY,
  command_name VARCHAR(96) NOT NULL,
  actor_id VARCHAR(128) NOT NULL,
  actor_type VARCHAR(32) NULL,
  idempotency_key VARCHAR(191) NOT NULL,
  request_digest CHAR(64) NOT NULL,
  request_json JSON NULL,
  status VARCHAR(32) NOT NULL,
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  result_json JSON NULL,
  result_ref VARCHAR(512) NULL,
  error_json JSON NULL,
  last_attempt_request_id VARCHAR(128) NULL,
  started_at DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  failed_at DATETIME(3) NULL,
  retain_until DATETIME(3) NULL,
  tombstoned_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY uk_command_idempotency_scope (command_name, actor_id, idempotency_key),
  KEY idx_command_idempotency_status (status, updated_at),
  KEY idx_command_idempotency_retention (retain_until, tombstoned_at)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS outbox_event (
  outbox_event_id VARCHAR(64) PRIMARY KEY,
  topic VARCHAR(128) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  schema_version VARCHAR(32) NOT NULL,
  source_name VARCHAR(96) NOT NULL,
  partition_key VARCHAR(191) NOT NULL,
  partition_position BIGINT UNSIGNED NOT NULL,
  aggregate_type VARCHAR(96) NOT NULL,
  aggregate_id VARCHAR(191) NOT NULL,
  aggregate_version BIGINT UNSIGNED NOT NULL,
  occurred_at DATETIME(3) NOT NULL,
  producer_version VARCHAR(64) NOT NULL,
  correlation_id VARCHAR(128) NULL,
  causation_id VARCHAR(128) NULL,
  idempotency_key VARCHAR(191) NOT NULL,
  dedupe_key VARCHAR(191) NOT NULL,
  payload_json JSON NOT NULL,
  payload_digest CHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  max_attempts INT UNSIGNED NOT NULL DEFAULT 5,
  available_at DATETIME(3) NOT NULL,
  next_retry_at DATETIME(3) NULL,
  lease_owner VARCHAR(128) NULL,
  lease_expires_at DATETIME(3) NULL,
  last_error_json JSON NULL,
  release_id VARCHAR(96) NULL,
  succeeded_at DATETIME(3) NULL,
  dead_lettered_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY uk_outbox_topic_dedupe (topic, dedupe_key),
  UNIQUE KEY uk_outbox_partition_position (source_name, partition_key, partition_position),
  KEY idx_outbox_dispatch (status, available_at, lease_expires_at, partition_position),
  KEY idx_outbox_aggregate_version (aggregate_type, aggregate_id, aggregate_version),
  KEY idx_outbox_release (release_id, created_at)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inbox_receipt (
  inbox_receipt_id VARCHAR(64) PRIMARY KEY,
  consumer_name VARCHAR(128) NOT NULL,
  source_name VARCHAR(96) NOT NULL,
  partition_key VARCHAR(191) NOT NULL,
  partition_position BIGINT UNSIGNED NOT NULL,
  event_id VARCHAR(64) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  schema_version VARCHAR(32) NOT NULL,
  aggregate_type VARCHAR(96) NOT NULL,
  aggregate_id VARCHAR(191) NOT NULL,
  aggregate_version BIGINT UNSIGNED NOT NULL,
  handler_version VARCHAR(64) NOT NULL,
  payload_json JSON NOT NULL,
  payload_digest CHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  attempt_count INT UNSIGNED NOT NULL DEFAULT 1,
  result_json JSON NULL,
  error_json JSON NULL,
  first_received_at DATETIME(3) NOT NULL,
  last_received_at DATETIME(3) NOT NULL,
  started_at DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  failed_at DATETIME(3) NULL,
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY uk_inbox_consumer_event (consumer_name, event_id),
  UNIQUE KEY uk_inbox_consumer_position (consumer_name, source_name, partition_key, partition_position),
  KEY idx_inbox_processing (consumer_name, status, updated_at),
  KEY idx_inbox_event (event_id, consumer_name)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS event_dead_letter (
  event_dead_letter_id VARCHAR(64) PRIMARY KEY,
  direction VARCHAR(16) NOT NULL,
  source_record_id VARCHAR(64) NOT NULL,
  consumer_name VARCHAR(128) NULL,
  source_name VARCHAR(96) NOT NULL,
  partition_key VARCHAR(191) NOT NULL,
  partition_position BIGINT UNSIGNED NOT NULL,
  event_id VARCHAR(64) NOT NULL,
  event_type VARCHAR(128) NOT NULL,
  payload_json JSON NULL,
  payload_digest CHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  attempt_count INT UNSIGNED NOT NULL DEFAULT 0,
  reason_code VARCHAR(64) NOT NULL,
  error_json JSON NULL,
  next_retry_at DATETIME(3) NULL,
  replay_request_id VARCHAR(128) NULL,
  release_id VARCHAR(96) NULL,
  first_failed_at DATETIME(3) NOT NULL,
  last_failed_at DATETIME(3) NOT NULL,
  resolved_at DATETIME(3) NULL,
  resolved_by VARCHAR(128) NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY uk_event_dead_letter_source (direction, source_record_id),
  KEY idx_event_dead_letter_open (status, next_retry_at, created_at),
  KEY idx_event_dead_letter_partition (consumer_name, source_name, partition_key, partition_position),
  KEY idx_event_dead_letter_event (event_id, status)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS consumer_checkpoint (
  consumer_checkpoint_id VARCHAR(64) PRIMARY KEY,
  consumer_name VARCHAR(128) NOT NULL,
  source_name VARCHAR(96) NOT NULL,
  partition_key VARCHAR(191) NOT NULL,
  last_contiguous_position BIGINT UNSIGNED NOT NULL DEFAULT 0,
  high_watermark_position BIGINT UNSIGNED NOT NULL DEFAULT 0,
  gap_status VARCHAR(32) NOT NULL,
  gap_from_position BIGINT UNSIGNED NULL,
  gap_to_position BIGINT UNSIGNED NULL,
  handler_version VARCHAR(64) NOT NULL,
  last_event_id VARCHAR(64) NULL,
  last_receipt_id VARCHAR(64) NULL,
  created_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY uk_consumer_checkpoint_partition (consumer_name, source_name, partition_key),
  KEY idx_consumer_checkpoint_gap (gap_status, updated_at)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
